echo "System Information"
echo "Hello, $LOGNAME"
echo "Current Date is = $(date)"
echo "User is `whoami`"
echo "Current Directory = $(pwd)"
echo "Network Name and Node Name = $(uname -n)"
echo "Kernal Name = $(uname -s)"
echo "Kernal Version = $(uname -v)"
echo "Kernal Release = $(uname -r)"
echo "Kernal OS = $(uname -o)"
echo "Processor Type = $(uname -p)"
echo "Kernal Machine Information = $(uname -m)"
echo "All Information = $(uname -a)"

